car-rental-notes/Models/ViewModels/Board/BoardVM.cs
using car_rental_notes.Models.Data;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace car_rental_notes.Models.ViewModels.Board
{
    public class BoardVM
    {
        public BoardVM() { }

        public BoardVM(BoardDTO row)
        {
            Board_Id = row.Board_Id;
            Rodzaj_Operacji_Id = row.Rodzaj_Operacji_Id;
            Rodzaj_Operacji = row.Rodzaj_Operacji;
            Miejsce_Operacji = row.Miejsce_Operacji;
            Zlecajacy = row.Zlecajacy;
            Data_Operacji = row.Data_Operacji;
            Godzina_Operacji = row.Godzina_Operacji;
            Nazwa_Klienta = row.Nazwa_Klienta;
            Telefon = row.Telefon;
            Samochod = row.Samochod;
            Klasa_Pojazdu = row.Klasa_Pojazdu;
            Uwagi = row.Uwagi;
            Wykonawca_Id = row.Wykonawca_Id;
            Wykonawca = row.Wykonawca;
        }

        public int Board_Id { get; set; }
        public string Rodzaj_Operacji { get; set; }
        public int Rodzaj_Operacji_Id { get; set; }
        public string Miejsce_Operacji { get; set; }
        public string Zlecajacy { get; set; }
        public DateTime Data_Operacji { get; set; }
        public TimeSpan Godzina_Operacji { get; set; }
        public string Nazwa_Klienta { get; set; }
        public string Telefon { get; set; }
        public string Samochod { get; set; }
        public string Klasa_Pojazdu { get; set; }
        public string Uwagi { get; set; }
        public string Wykonawca { get; set; }
        public int Wykonawca_Id { get; set; }


        public IEnumerable<SelectListItem> Operations { get; set; }
    }
}

car-rental-notes/Models/ViewModels/Board/Operations.cs
using car_rental_notes.Models.Data;

namespace car_rental_notes.Models.ViewModels.Board
{
    public class Operations
    {
        public Operations() { }

        public Operations(OperationsDTO row)
        {
            Operations_Id = row.Operations_Id;
            Nazwa = row.Nazwa;
        }

        public int Operations_Id { get; set; }
        public string Nazwa { get; set; }
    }
}

car-rental-notes/Controllers/BoardController.cs
using car_rental_notes.Models.Data;
using car_rental_notes.Models.ViewModels.Board;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace car_rental_notes.Controllers
{
    public class BoardController : Controller
    {
        // GET: Board
        public ActionResult Index(bool flag = true, int numberOfDays = 0, string whichDay = "01/01/2020")
        {
            if (flag == true)
            {
                TempData["SelectedDate"] = System.DateTime.Now.Add(new TimeSpan(0, 0, 0, 0)).ToString("dd/MM/yyyy");
                TempData["NumberOfDays"] = 0;
            }
            else
            { 
                TempData["SelectedDate"] = whichDay;
                TempData["NumberOfDays"] = numberOfDays;
            }

            List<BoardVM> boardList;

            using (Db db = new Db())
            {
                boardList = db.Board.ToArray().Select(x => new BoardVM(x)).ToList();
                TempData["Counter"] = boardList.Where(x => x.Data_Operacji == Convert.ToDateTime(TempData["SelectedDate"])).Count();
            }

            
            return View(boardList);
        }

        // GET: Board/NextDay
        [HttpGet]
        public ActionResult NextDay()
        {
            int numberOfDays = Convert.ToInt32(TempData["NumberOfDays"]);

            TempData["NumberOfDays"] = numberOfDays++;

            TempData["SelectedDate"] = System.DateTime.Now.Add(new TimeSpan(numberOfDays, 0, 0, 0)).ToString("dd/MM/yyyy");

            string whichDay = TempData["SelectedDate"].ToString();


            return RedirectToAction("Index", new { flag = false, numberOfDays, whichDay });
        }

        // GET: Board/PreviousDay
        [HttpGet]
        public ActionResult PreviousDay()
        {
            int numberOfDays = Convert.ToInt32(TempData["NumberOfDays"]);

            TempData["NumberOfDays"] = numberOfDays--;

            TempData["SelectedDate"] = System.DateTime.Now.Add(new TimeSpan(numberOfDays, 0, 0, 0)).ToString("dd/MM/yyyy");

            string whichDay = TempData["SelectedDate"].ToString();


            return RedirectToAction("Index", new { flag = false, numberOfDays, whichDay });
        }

        [HttpGet]
        public ActionResult AddNewNote()
        {
            System.DateTime moment = System.DateTime.Now.Add(new TimeSpan(0, 0, 0, 0));
            BoardVM boardVM = new BoardVM();
            TempData["thisDay"] = System.DateTime.Now.Add(new TimeSpan(0, 0, 0, 0)).ToString("dd/MM/yyyy");
            TempData["thisHour"] = moment.Hour +":"+ moment.Minute;

            using (Db db = new Db())
            {
                boardVM.Operations = new SelectList(db.Operations.ToList(), "Operations_Id", "Nazwa");
            }

            return PartialView(boardVM);
        }

        [HttpPost]
        public ActionResult AddNewNote(BoardVM boardVM)
        {
            if (boardVM.Rodzaj_Operacji_Id == 0) {
                return View(boardVM);
            }

            if (!ModelState.IsValid)
            {
                return View(boardVM);
            }

            using (Db db = new Db())
            {
                OperationsDTO opDTO = db.Operations.FirstOrDefault(x => x.Operations_Id == boardVM.Rodzaj_Operacji_Id);

                BoardDTO newNote = new BoardDTO
                {
                    Data_Operacji = boardVM.Data_Operacji,
                    Miejsce_Operacji = boardVM.Miejsce_Operacji,
                    Klasa_Pojazdu = boardVM.Klasa_Pojazdu,
                    Godzina_Operacji = boardVM.Godzina_Operacji,
                    Zlecajacy = boardVM.Zlecajacy,
                    Nazwa_Klienta = boardVM.Nazwa_Klienta,
                    Telefon = boardVM.Telefon,
                    Samochod = boardVM.Samochod,
                    Uwagi = boardVM.Uwagi,
                    Rodzaj_Operacji = opDTO.Nazwa,
                    Rodzaj_Operacji_Id = boardVM.Rodzaj_Operacji_Id,
                    Wykonawca = "-",
                    Wykonawca_Id = 0
                };

                db.Board.Add(newNote);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        // GET: Board/DeleteNote
        [HttpGet]
        public ActionResult DeleteNote(int id)
        {
            using (Db db = new Db())
            {
                BoardDTO dto = db.Board.Find(id);
                db.Board.Remove(dto);
                db.SaveChanges();
            }

            try
            {
                int numberOfDays = Convert.ToInt32(TempData["NumberOfDays"]);
                string whichDay = TempData["SelectedDate"].ToString();
                return RedirectToAction("Index", new { flag = false, numberOfDays, whichDay });
            }
            catch (NullReferenceException e)
            {
                Console.WriteLine(e);
                return RedirectToAction("Index");
            }

        }

        // GET: Board/IllDoIt
        [HttpGet]
        public ActionResult IllDoIt(string userName, int noteId)
        {
            using (Db db = new Db())
            {
                BoardDTO note = db.Board.Find(noteId);
                UsersDTO user = db.Users.FirstOrDefault(x => x.Login == userName);
                note.Wykonawca = userName;
                note.Wykonawca_Id = user.User_Id;
                db.SaveChanges();
            }
            
            return RedirectToAction("Index");
        }

        // GET: Board/IllNotDoIt
        [HttpGet]
        public ActionResult IllNotDoIt(int noteId)
        {
            using (Db db = new Db())
            {
                BoardDTO note = db.Board.Find(noteId);
                note.Wykonawca = "-";
                note.Wykonawca_Id = 0;
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }




    }
}

car-rental-notes/Views/Board/AddNewNote.cshtml
@model car_rental_notes.Models.ViewModels.Board.BoardVM
@if (Request.IsAuthenticated)
{
    <link href="~/StylesCSS/Board/AddNewNoteCSS.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Rajdhani&display=swap&subset=latin-ext" rel="stylesheet">
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    using (@Html.BeginForm("AddNewNote", "Board", FormMethod.Post, htmlAttributes: new { @id = "add-main-box" }))
    {
        <div id="add-new-note-box">
            <div id="information-box"><span>DODAJ NOWE ZLECENIE</span></div>
            <div id="">@Html.DropDownListFor(model => model.Rodzaj_Operacji_Id, Model.Operations, "wybierz rodzaj zlecenia", new { @class = "rodzaj-operacji" })</div>
            <ul id="add-new-note-list">
                <li>
                    @Html.EditorFor(model => model.Data_Operacji, new { htmlAttributes = new { @Value = TempData["thisDay"], @class = "data-operacji editors", @type = "text", @id = "datepicker" } })
                    @Html.EditorFor(model => model.Godzina_Operacji, new { htmlAttributes = new { @Value = TempData["thisHour"], @class = "godzina-operacji editors" } })
                </li>
                <li>
                    @Html.EditorFor(model => model.Klasa_Pojazdu, new { htmlAttributes = new { @placeholder = " klasa pojazdu ", @class = "klasa-pojazdu editors" } })
                    @Html.EditorFor(model => model.Samochod, new { htmlAttributes = new { @placeholder = " samochód / rejestracja ", @class = "samochod editors" } })
                </li>
                <li>
                    @Html.EditorFor(model => model.Miejsce_Operacji, new { htmlAttributes = new { @placeholder = " miejsce operacji ", @class = "miejsce-operacji editors" } })
                </li>
                <li>
                    @Html.EditorFor(model => model.Nazwa_Klienta, new { htmlAttributes = new { @placeholder = " nazwa klienta ", @class = "nazwa-klienta editors" } })
                </li>
                <li>
                    @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @placeholder = " telefon ", @class = "telefon  editors" } })
                </li>
                <li>
                    @Html.EditorFor(model => model.Zlecajacy, new { htmlAttributes = new { @placeholder = " zlecający ", @class = "zlecajacy editors" } })
                </li>
            </ul>
            <div id="uwagi-box"> @Html.TextAreaFor(model => model.Uwagi, new { @placeholder = " uwagi [max 200 słów]", @class = "uwagi editors" })</div>
            <button id="add-note-btn"><strong>WYŚLIJ</strong></button>
        </div>
        @Scripts.Render("~/bundles/addnewnote")
    }
}
else
{
    <script type="text/javascript">
         $(function(){ window.location.href = "@Url.Action("Login","Account")";});
    </script>
}

car-rental-notes/Views/Board/Index.cshtml
@model IEnumerable<car_rental_notes.Models.ViewModels.Board.BoardVM>
@if (Request.IsAuthenticated)
{
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <link href="~/StylesCSS/Board/IndexCSS.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/board_index")
    {
        ViewBag.Title = "Tablica";
    }
    <link rel="shortcut icon" href="">
    <body>
        <div id="board-top-bar"></div>
        <div id="mobile-board-index-top-tools-bar">
            @section mobile_top_tools_bar{
                <div id="mobile-top-tools-box-1" class="mobile-top same-width"> <span>@TempData["Counter"]</span> </div>
                <div id="mobile-top-tools-box-2" class="mobile-top same-width"> <a class="fas fa-angle-left"></a> </div>
                <div id="mobile-top-tools-box-3" class="mobile-top"> <span>@TempData["SelectedDate"]</span> </div>
                <div id="mobile-top-tools-box-4" class="mobile-top same-width"> <a class="fas fa-angle-right"></a> </div>
                @if (User.IsInRole("Administrator")){<div id="mobile-top-tools-box-5" class="mobile-top same-width"> <i class="fas fa-angle-double-down" id="mobile-btn-addnewnote"></i> </div>}
                else if (User.IsInRole("Kierowca")){<div id="mobile-top-tools-box-5" class="mobile-top same-width"></div>}
            }
        </div>
        <div id="board-index-top-tools-bar">
            @section top_tools_bar{
                <div id="top-tools-box-1"> <span>@TempData["Counter"]</span> </div>
                <div id="top-tools-box-2"> <a class="fas fa-angle-left"></a> </div>
                <div id="top-tools-box-3"> <span>@TempData["SelectedDate"]</span> </div>
                <div id="top-tools-box-4"> <a class="fas fa-angle-right"></a> </div>
                @if (User.IsInRole("Administrator")){<div id="top-tools-box-5"> <i class="fas fa-angle-double-down" id="btn-addnewnote"></i> </div>}
                else if (User.IsInRole("Kierowca")){<div id="top-tools-box-5"></div>}
            }
        </div>
        <div id="add-new-note-content">
            @Html.Action("AddNewNote", "Board", new { area = "" })
        </div>
        <ul id="table">
            @foreach (var item in Model)
            {
                if (item.Data_Operacji.ToString("dd/MM/yyyy") == @TempData["SelectedDate"].ToString())
                {
                    <li onload="">
                        <div class="single-note-box" id="@item.Board_Id" accesskey="9" onload="single-note-transform()">
                            <div class="front-note-side max-width max-height">
                                @if (item.Wykonawca == "-"){<div class="front-box-1 max-width"></div>}
                                else if (item.Wykonawca != "-")
                                {<div class="front-box-1 max-width" style="border-bottom: 0.1em solid white;">wykonuje: @item.Wykonawca</div>}
                                <div class="front-box-2 max-width">@item.Rodzaj_Operacji</div>
                                <div class="front-box-3 max-width">@item.Miejsce_Operacji</div>
                                <div class="front-box-4 max-width">klasa @item.Klasa_Pojazdu</div>
                                <div class="front-box-5 max-width">@item.Godzina_Operacji.ToString("hh':'mm")</div>
                            </div>
                            <div class="back-note-side max-width max-height">
                                <div class="back-side-menu max-width" onmouseover="show_back_menu(this)" onmouseout="hide_back_menu(this)">
                                    @if (item.Wykonawca == "-"){<div class="add-btn-box back-btn-box max-height"><a style="color:#ebfafa;" class="fas fa-plus add-option-img" href="~/Board/IllDoIt/?userName=@User.Identity.Name&noteId=@item.Board_Id"></a></div>}
                                    else if (item.Wykonawca != "-")
                                    {
                                        if (item.Wykonawca == User.Identity.Name){<div class="add-btn-box back-btn-box max-height"><a style="color:#ebfafa;" class="fas fa-minus add-option-img delete-two" href="~/Board/IllNotDoIt/?noteId=@item.Board_Id"></a></div>}
                                        else if (item.Wykonawca != User.Identity.Name){<div class="add-btn-box back-btn-box max-height"><a style="color:#ebfafa;" class="fas fa-check add-option-img change" href="~/Board/IllDoIt/?userName=@User.Identity.Name&noteId=@item.Board_Id"></a></div>}
                                    }
                                    <div class="edit-btn-box back-btn-box max-height"></div>
                                    <div class="space-for-new-btn"></div>
                                    @if (User.IsInRole("Administrator")){<div class="delete-btn-box back-btn-box max-height"><a style="color:#ebfafa;" class="fas fa-times delete-option-img delete" href="/Board/DeleteNote/@item.Board_Id"></a></div>}
                                    else if (User.IsInRole("Administrator")){<div class="delete-btn-box back-btn-box max-height"></div>}
                                </div>
                                <div class="back-side-content max-width max-height">
                                    <div class="back-box-1 max-width">@item.Zlecajacy</div>
                                    <div class="back-box-2 max-width">@item.Nazwa_Klienta</div>
                                    <div class="back-box-3 max-width">@item.Telefon</div>
                                    <div class="back-box-4 max-width"> @item.Samochod</div>
                                    <div class="back-box-5 max-width"> @item.Uwagi</div>
                                </div>
                            </div>
                        </div>
                        <script>set_note_layout('@item.Rodzaj_Operacji',@item.Board_Id);</script>
                    </li>
                }
            }
            <li></li>
        </ul>
        @Scripts.Render("~/bundles/board_index")
    </body>
}
else
{
    <script type="text/javascript">
         $(function(){ window.location.href = "@Url.Action("Login","Account")";});
    </script>
}