car-rental-notes/Models/ViewModels/Wall/AnnouncementsVM.cs
using car_rental_notes.Models.Data;
using System;

namespace car_rental_notes.Models.ViewModels.Wall
{
    public class AnnouncementsVM
    {
        public AnnouncementsVM() { }

        public AnnouncementsVM(AnnouncementsDTO row) {
            Announcement_Id = row.Announcement_Id;
            Data = row.Data;
            Autor = row.Autor;
            Temat = row.Temat;
            Tresc = row.Tresc;
        }

        public int Announcement_Id { get; set; }
        public DateTime Data { get; set; }
        public string Autor { get; set; }
        public string Temat { get; set; }
        public string Tresc { get; set; }
    }
}

car-rental-notes/Controllers/WallController.cs
using car_rental_notes.Models.Data;
using car_rental_notes.Models.ViewModels.Wall;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace car_rental_notes.Controllers
{
    public class WallController : Controller
    {
        // GET: Wall
        public ActionResult Index()
        {
            int todayCount, yourCount;
            string userName = User.Identity.Name;
            DateTime today = Convert.ToDateTime(System.DateTime.Now.Add(new TimeSpan(0, 0, 0, 0)).ToString("dd/MM/yyyy"));
            List<AnnouncementsVM> AnnouncementsList;
            using (Db db = new Db())
            {
                AnnouncementsList = db.Announcements.ToArray().Select(x => new AnnouncementsVM(x)).ToList();
                todayCount = db.Board.Where(x => x.Data_Operacji == today).Count();
                yourCount = db.Board.Where(x => x.Data_Operacji == today && x.Wykonawca == userName).Count();
            }

            if (todayCount == 0) TempData["Today"] = "Brak zaplanowanych zleceń w dniu dzisiejszym"; 
            else if (todayCount == 1) TempData["Today"] = "Dzisiaj mamy jedno zaplanowane zlecenie ";
            else if (todayCount > 1 && todayCount < 5 ) TempData["Today"] = "Dzisiaj mamy " + todayCount + " zaplanowane zlecenia";
            else if (todayCount > 2) TempData["Today"] = "Dzisiaj mamy " + todayCount + " zaplanowanych zleceń";


            if (todayCount != 0 && yourCount == 0) TempData["YourOp"] = "."; 
            else if (yourCount == 1) TempData["YourOp"] = ", jedno należy do Ciebie.";
            else if (yourCount > 1) TempData["YourOp"] = ", " + yourCount + " należy do Ciebie.";

            return View(AnnouncementsList);
        }

        [HttpGet]
        public ActionResult AddAnnouncement()
        {
            AnnouncementsVM AnnouncementVM = new AnnouncementsVM();

            return PartialView(AnnouncementVM);

        }

        [HttpPost]
        public ActionResult AddAnnouncement(AnnouncementsVM model)
        {
            string userName = User.Identity.Name;

            using (Db db = new Db())
            {
                AnnouncementsDTO AnnDTO = new AnnouncementsDTO
                {
                    Temat = model.Temat,
                    Tresc = model.Tresc,
                    Data = System.DateTime.Now.Add(new TimeSpan(0, 0, 0, 0)),
                    Autor = userName
                };

                db.Announcements.Add(AnnDTO);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        // GET: Wall/DeleteAnnouncement
        [HttpGet]
        public ActionResult DeleteAnnouncement(int id)
        {

            using (Db db = new Db())
            {
                AnnouncementsDTO dto = db.Announcements.Find(id);
                db.Announcements.Remove(dto);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

car-rental-notes/Views/Wall/AddAnnouncement.cshtml
@model car_rental_notes.Models.ViewModels.Wall.AnnouncementsVM
@if (Request.IsAuthenticated)
{
    <link href="~/StylesCSS/Wall/AnnouncementsCSS.css" rel="stylesheet" />
    using (@Html.BeginForm("AddAnnouncement", "Wall", FormMethod.Post, htmlAttributes: new { @id = "add-new-ann-main" }))
    {
        <div id="add-new-ann-box">
            <div id="information-box"><span>DODAJ NOWE OGŁOSZENIE</span></div>
            <div class="box"> @Html.EditorFor(model => model.Temat, new { htmlAttributes = new { @placeholder = " temat ", @class = "temat editors" } })</div>
            <div class="box"> @Html.TextAreaFor(model => model.Tresc, new { @placeholder = " uwagi [max 200 słów]", @class = "uwagi editors" })</div>
            <button id="add-ann-btn"><strong>WYŚLIJ</strong></button>
        </div>
    }
}
else
{
    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript">
         $(function(){ window.location.href = "@Url.Action("Login","Account")";});
    </script>
}

car-rental-notes/Views/Wall/Index.cshtml
@model IEnumerable<car_rental_notes.Models.ViewModels.Wall.AnnouncementsVM>
<link href="https://fonts.googleapis.com/css?family=Rajdhani&display=swap&subset=latin-ext" rel="stylesheet">
<link href="~/StylesCSS/Wall/AnnouncementsCSS.css" rel="stylesheet" />
@Scripts.Render("~/bundles/wall")
@if (Request.IsAuthenticated)
{
    {
        ViewBag.Title = "Ogłoszenia";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    @section mobile_top_tools_bar{
        <div id="mobile-ann-top-tools-box-1" class="top-mobile"> </div>
        <div id="mobile-ann-top-tools-box-2" class="top-mobile"><span class="mobile-be-center">OGŁOSZENIA</span></div>
        @if (User.IsInRole("Administrator")){<div id="mobile-ann-top-tools-box-3" class="top-mobile"><i class="fas fa-plus be-center" id="mobile-add-new-ann-btn"></i></div>}
        else if (User.IsInRole("Kierowca")){<div id="mobile-ann-top-tools-box-3" class="top-mobile"></div>}
    }
    @section top_tools_bar{
        <div id="ann-top-tools-box-1"></div>
        <div id="ann-top-tools-box-2"><span class="be-center">OGŁOSZENIA</span></div>
        @if (User.IsInRole("Administrator")){<div id="ann-top-tools-box-3"><i class="fas fa-plus be-center" id="add-new-ann-btn"></i></div>}
        else if (User.IsInRole("Kierowca")){<div id="ann-top-tools-box-3"></div>}
    }
    <div id="anns">
        <ul id="ann-table">
            @if (User.Identity.IsAuthenticated)
            {
                <li><div class="ann-daily-info"><strong>Cześć @User.Identity.Name! @TempData["Today"]@TempData["YourOp"]</strong></div></li>
            }
            <li><div id="add-new-ann">@Html.Action("AddAnnouncement", "Wall", new { area = "" })</div></li>
            @foreach (var item in Model.Reverse())
            {
                <li>
                    <div class="ann-main-box">
                        <div class="ann-subject">
                            <b>@item.Temat</b>
                            @if (User.IsInRole("Administrator")){<a href="/Wall/DeleteAnnouncement/@item.Announcement_Id" class="delete">[ usuń ogłoszenie ]</a>}
                        </div>
                        <div class="ann-content">@item.Tresc</div>
                        <div class="ann-author">utworzono <i>@item.Data.Date.ToString("dd.MM.yyyy")</i> przez <i>@item.Autor</i></div>
                    </div>
                </li>
            }
        </ul>
    </div>
}
else
{
    <script type="text/javascript">
    $(function(){ window.location.href = "@Url.Action("Login", "Account")"; });
    </script>
}